title: Christopher Miao
Description: Currently looking for a full-time Software Engineering job starting Summer of 2025
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
